### ISSUE TITLE
Can I take over this repo?

### ISSUE THREAD

**Issue by acconrad** [BennyHallett/obelisk#51]
@BennyHallett I see from your personal website that you agree this isn't maintained anymore. It is, however, still widely used. I love using Obelisk, but it does need to be updated for newer versions of Elixir and the issue count is growing.

Since I use Obelisk for all of my personal sites, and I like the software, I'd like to ask if it would be alright if I created a fork of Obelisk and moved that over to be the official branch of the project (with your permission, of course)? I'd be happy to take over all of the issues as well. 

If that's something you're okay with, let me know so I can get started on working with it. I would have emailed you but your email is difficult to track and this seemed to be the best place I could make this offer.

**Comment by subsoap** [comment]
You should fork it and begin to maintain on that fork for now.

**Comment by acconrad** [comment]
@subsoap I would but generally you have to get permission first, because places like Awesome-elixir will still point to @BennyHallett 's branch and people need to know where to go for the currently-maintained version

**Comment by subsoap** [comment]
You do not need permission to fork it and begin to make any necessary changes now. At the very least, you can make pull requests of your changes.

**Comment by acconrad** [comment]
@subsoap well my main point is under `Settings` you can choose **Transfer ownership** which is what I'm getting at - this allows me to maintain all of the same issues and helps everyone reference the same primary repo without having two fragmented branches. It just makes it cleaner and easier for everyone

**Comment by subsoap** [comment]
He doesn't need to transfer ownership nor should he, just add you as a collaborator here https://github.com/BennyHallett/obelisk/settings/collaboration . Then you can merge your own pull requests into this repo from your fork.

**Comment by acconrad** [comment]
@subsoap except I don't have access to that page so I can't add myself as a collaborator, is there another alternative?

**Comment by doomspork** [comment]
@acconrad I might suggest you start by making improvements and opening PRs.  If @BennyHallett is onboard with the direction you're taking the project there's no reason not to add you.  Generally speaking though folks aren't added as contributors until they've contributed to the project.  

I will say this: I've forked this project and am working on some updates, albeit slowly, to update the dependencies and improve the support for haml, slim, etc.  If @BennyHallett isn't interested in them?  That's okay, I'll continue to use my fork.  My goal in this endeavor is to get to a point of being able to operate elixirschool.com on Elixir and not Jekyll/Ruby.

**Comment by acconrad** [comment]
@doomspork yes my thought was to indeed add a bunch of PRs to fix things, but i noticed that he hasn't been approving or committing them.  I may want to work on your branch since I've been doing much the same work and also trying to add in new features - and in fact I have the _exact_ same goal as you in wanting to operate my own static sites with Elixir/Obelisk instead of Jekyll/Ruby. Do you have any interest in collaborating?

**Comment by doomspork** [comment]
@acconrad it does look like the maintainer commented on those PRs as to why they couldn't merge: it is due to project dependencies.

I'd more than welcome the additional help!  To be honest after spending a good chunk of time digging into Obelisk and making improvements I'm not quite sure it's worth the effort anymore.  Could very likely step back, rethink things, and take a different approach and end up with a more maintainable codebase with little to no dependencies.

I'm on Elixir Slack with the same handle if you wanna shoot me a message.

**Comment by FreedomBen** [comment]
I hope something comes of this.  I'm also wanting to move from Jekyll to Obelisk, and am happy to send PRs, if they will be reviewed and merged if desired. 

I like the idea of rethinking things actually.  There's some things that Jekyll does that Obelisk can't do, that would be really nice.  Like creating sub directories for pages so that the URL can be:

    https://example.com/about/

Instead of 

    https://example.com/about.html

It's a small thing, but I much prefer the URLs without extension.  It makes for a consistent experience when paired with a Phoenix app, and just feels cleaner overall.

I also want to add a mix task for generating pages.  At this point I'm tempted to just return to Jekyll unless things move forward here.  If they do, I can help out as well.
